### ISSUE TITLE
No kernel image is available for execution on the device

### ISSUE THREAD

**Issue by JibKh** [Gauravv97/flownet2-Colab#1]
I made the runtime GPU and added the line in all three setup.py. My Google Colab is running on Tesla K80
`'-gencode', 'arch=compute_37,code=sm_37',`

However I still receive the error:
`error in correlation_forward_cuda_kernel: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "main.py", line 416, in <module>
    stats = inference(args=args, epoch=epoch - 1, data_loader=inference_loader, model=model_and_loss, offset=offset)
  File "main.py", line 374, in inference
    losses, output = model(data[0], target[0], inference=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 172, in forward
    output = self.model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/flownet2pytorch/models.py", line 129, in forward
    flownetc_flow2 = self.flownetc(x)[0]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/flownet2pytorch/networks/FlowNetC.py", line 86, in forward
    out_corr = self.corr(out_conv3a, out_conv3b) # False
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/flownet2pytorch/networks/correlation_package/correlation.py", line 58, in forward
    result = CorrelationFunction.apply(input1, input2, self.pad_size, self.kernel_size, self.max_displacement, self.stride1, self.stride2, self.corr_multiply)
  File "/content/flownet2pytorch/networks/correlation_package/correlation.py", line 25, in forward
    ctx.pad_size, ctx.kernel_size, ctx.max_displacement, ctx.stride1, ctx.stride2, ctx.corr_multiply)
RuntimeError: CUDA call failed (correlation_forward_cuda at correlation_cuda.cc:82)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7efe78c15fe1 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7efe78c15dfa in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #2: correlation_forward_cuda(at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, int, int, int, int, int, int) + 0x624 (0x7efe72bc6244 in /root/.local/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x14c0a (0x7efe72bd1c0a in /root/.local/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x11e07 (0x7efe72bcee07 in /root/.local/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #5: ./output() [0x50a7f5]
frame #6: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in ./output)
frame #7: ./output() [0x507f24]
frame #8: ./output() [0x588f1d]
frame #9: PyObject_Call + 0x3e (0x59fe1e in ./output)
frame #10: THPFunction_apply(_object*, _object*) + 0x581 (0x7efeb2f474d1 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #11: ./output() [0x50a47f]
frame #12: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in ./output)
frame #13: _PyFunction_FastCallDict + 0xf5 (0x509015 in ./output)
frame #14: ./output() [0x594b01]
frame #15: PyObject_Call + 0x3e (0x59fe1e in ./output)
frame #16: _PyEval_EvalFrameDefault + 0x17e6 (0x50d596 in ./output)
frame #17: ./output() [0x507f24]
frame #18: _PyFunction_FastCallDict + 0x2e2 (0x509202 in ./output)
frame #19: ./output() [0x594b01]
frame #20: ./output() [0x54ac61]
frame #21: _PyObject_FastCallKeywords + 0x19c (0x5a9eec in ./output)
frame #22: ./output() [0x50a783]
frame #23: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in ./output)
frame #24: _PyFunction_FastCallDict + 0xf5 (0x509015 in ./output)
frame #25: ./output() [0x594b01]
frame #26: PyObject_Call + 0x3e (0x59fe1e in ./output)
frame #27: _PyEval_EvalFrameDefault + 0x17e6 (0x50d596 in ./output)
frame #28: ./output() [0x507f24]
frame #29: _PyFunction_FastCallDict + 0x2e2 (0x509202 in ./output)
frame #30: ./output() [0x594b01]
frame #31: ./output() [0x54ac61]
frame #32: _PyObject_FastCallKeywords + 0x19c (0x5a9eec in ./output)
frame #33: ./output() [0x50a783]
frame #34: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in ./output)
frame #35: _PyFunction_FastCallDict + 0xf5 (0x509015 in ./output)
frame #36: ./output() [0x594b01]
frame #37: PyObject_Call + 0x3e (0x59fe1e in ./output)
frame #38: _PyEval_EvalFrameDefault + 0x17e6 (0x50d596 in ./output)
frame #39: ./output() [0x507f24]
frame #40: _PyFunction_FastCallDict + 0x2e2 (0x509202 in ./output)
frame #41: ./output() [0x594b01]
frame #42: ./output() [0x54ac61]
frame #43: _PyObject_FastCallKeywords + 0x19c (0x5a9eec in ./output)
frame #44: ./output() [0x50a783]
frame #45: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in ./output)
frame #46: ./output() [0x507f24]
frame #47: _PyFunction_FastCallDict + 0x2e2 (0x509202 in ./output)
frame #48: ./output() [0x594b01]
frame #49: PyObject_Call + 0x3e (0x59fe1e in ./output)
frame #50: _PyEval_EvalFrameDefault + 0x17e6 (0x50d596 in ./output)
frame #51: ./output() [0x507f24]
frame #52: _PyFunction_FastCallDict + 0x2e2 (0x509202 in ./output)
frame #53: ./output() [0x594b01]
frame #54: ./output() [0x54ac61]
frame #55: PyObject_Call + 0x3e (0x59fe1e in ./output)
frame #56: _PyEval_EvalFrameDefault + 0x17e6 (0x50d596 in ./output)
frame #57: ./output() [0x507f24]
frame #58: _PyFunction_FastCallDict + 0x2e2 (0x509202 in ./output)
frame #59: ./output() [0x594b01]
frame #60: PyObject_Call + 0x3e (0x59fe1e in ./output)
frame #61: _PyEval_EvalFrameDefault + 0x17e6 (0x50d596 in ./output)
frame #62: ./output() [0x507f24]
frame #63: _PyFunction_FastCallDict + 0x2e2 (0x509202 in ./output)`

Any help?

**Comment by Gauravv97** [comment]
Hi @JibKh , Thanks. I did encounter this error but was never able to replicate it. My code worked fine on K80 (in my last test) without any changes to the original Flownet2 repository. Well, there is no easy way around it without creating a fork of Flownet and changing the codes in the setup files. Nevertheless I have done just that. Glad you updated me on the incident.
