### ISSUE TITLE
forward backward flo

### ISSUE THREAD

**Issue by xn-ml-sia** [Gauravv97/flownet2-Colab#2]
I'm trying to generate forward backward flo files for this neural_style transfer as required by this repo. It is using the old flownet was wondering if you run into this before

https://github.com/dvschultz/neural-style-tf

**Comment by Gauravv97** [comment]
Hi @xn-ml-sia , I was also initially interested in style transfer and came across this project too.

The forward flow is already being generated in my current code.

0001.jpg 0002.jpg generates 0001.flo ( Rename this to forward_1_2.flo for it to work in this project)

0001.jpg  warped with 0001.flo will give you 0002.jpg.

As for the backward flow there is no in line method. You can rename the files in reverse order and again rename the generated flo files or 

Generate individual flo for each pair of image for example 0002.jpg 0001.jpg gives you 0001.flo ( Rename this to backward_2_1.flo for it to work in this project)

single image pair flo can be generated using this [code](https://github.com/NVIDIA/flownet2-pytorch/issues/51#issuecomment-398301033)

I had the modified the above code (lost it) so I know it works. You might need to do some changes too. .ppm can be replaced with .png/.jpg files too.

Hope this helps. Let me know if you have already solved this.
