### ISSUE TITLE
Run the repo locally

### ISSUE THREAD

**Issue by sotomotocross** [Gauravv97/flownet2-Colab#4]
Hey NN entry level user here and i'm struggling to use FlowNet 2.

In your README.md you mention that: The simple git clone method doesn't work with flownet2 when running it on Google Colab. Some additional steps are required to make it work.
If i want to run this repo NN locally creating my own dataset (i have the footage and i want to create the .flo files) what are these additional steps required to make it work?

Thank you very much in advance for your help and amazing work.

**Comment by Gauravv97** [comment]
As long as you have a good Nvidia GPU , latest drivers , compatible cuDNN and Cuda installed, there won't be any issues..
The additional steps are already implemented in my colab notebook, there were some library and path mismatches while running flownet on google colab, fixed those in this notebook.

**Comment by sotomotocross** [comment]
So if i create my own video.mp4 and upload it in the Google Colab folder i can run all the Notebook creating my own small dataset for testing of pre-trained network?

**Comment by sotomotocross** [comment]
Have you create your own training dataset according to MPI Sintel Dataset?

**Comment by CLD24** [comment]
How to deal with "ModuleNotFoundError: No module named 'resample2d_cuda"? Thank you

**Comment by Gauravv97** [comment]
Hi @sotomotocross, Yes if you upload your own video.mp4 as mentioned in the notebook, your video will be used for infrence.
Hi @CLD24 , Are you running the notebook present in this repository? The code should run fine as long as all the steps mentioned in the notebook are executed.
