### ISSUE TITLE
Problems to run the code

### ISSUE THREAD

**Issue by SaraLCO99** [Gauravv97/flownet2-Colab#6]
Hi! 
I am trying to run the code but I have problems in the part of "Generate .flo files using FlowNet2" because when it is trying to Build FlowNet2 model it says that can not Loading checkpoint './FlowNet2_checkpoint.pth.tar' and the operation is failed also said that: 

Traceback (most recent call last):
 File "main.py", line 210, in <module>
    checkpoint = torch.load(args.resume)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

when I go to the serialization.py there are errors on: 
from ._utils import _import_dotted_name
from ._six import string_classes as _string_classes
It said that ._utils and ._six can not be resolved 

I am running on cuda_11.1 I do not know if can be a conflict with the versions. I would like to know if you can help me to know what can I do.

Thanks in advance, 

Regards,

**Comment by Gauravv97** [comment]
Hi @SaraLCO99, Quick Ques, Are you running this code in your own env.? If so please make sure the libraries & paths are correctly installed & set.

I had made this notebook to work specifically on colab after several trial and error with various CUDA &  Pytorch versions. This has high GPU requirements thus it didn't work on my older setup. I would suggest you use this colab notebook for your run.

Apart from this, please make sure you have downloaded the Flownet Model & placed it in correct path as per the command.

Regard,

**Comment by Gauravv97** [comment]
Hi @SaraLCO99, It seems that the model is not correctly being downloaded from [google drive](https://drive.google.com/u/0/uc?id=1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da&export=download).

I suggest you download & upload it directly or create a new link from your personal Drive.

Regards,

**Comment by SaraLCO99** [comment]
Hi, it works thank youuu!!

Regards,
